---
title: "Cuestionario sobre Intención de Voto 2026"
author: "Josué Redondo"
date: "2025-10-02"
output: html_document
---

# Intención de voto de cara a las elecciones presidenciales del 2026

## Introducción:

### Propósito del cuestionario:

El siguiente cuestionario tiene el propósito de conocer la intención de voto de cara a las próximas elecciones presidenciales de Costa Rica del 2026. 

### Importancia del estudio:

La importancia de este cuestionario radica en conocer expectativas de voto que tiene la población del CUC con respecto a las distintas candidaturas presidenciales que se han presentado hasta octubre del 2025.






=======================================================================================

Las personas que gusten colaborar con este cuestionario deben contestar con total sinceridad las preguntas planteadas en el cuestionario, las cuales se presentan en forma de preguntas dicotómicas (preguntas cuya respuesta es Si/No), preguntas de opción múltiple, preguntas de escala Likert (Muy bueno, bueno, regular, malo, muy malo), preguntas




